# Generated by Django 3.1.2 on 2020-10-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
