# Generated by Django 3.1.2 on 2020-10-31 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
