# Generated by Django 3.1.2 on 2020-10-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='artist',
            new_name='Artists',
        ),
    ]
