# Generated by Django 3.1.2 on 2020-10-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_artists_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('style', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='static/image/')),
            ],
        ),
    ]
