# Generated by Django 3.1.2 on 2020-10-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_customer_order_orderitem_painting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='painting',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
