# Generated by Django 3.1.2 on 2020-10-25 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_delete_geeksmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='artist',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
