# Generated by Django 3.1.2 on 2020-10-27 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
