# Generated by Django 3.1.2 on 2020-10-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='g_id',
        ),
    ]
