# Generated by Django 3.1.2 on 2020-10-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_remove_gallery_g_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artists',
            name='a_id',
        ),
    ]
