# Generated by Django 3.1.2 on 2020-10-27 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_remove_artists_a_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='painting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.painting'),
        ),
    ]
