# Generated by Django 3.1.2 on 2020-10-27 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_artists_painting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artists',
            name='painting',
        ),
        migrations.AlterField(
            model_name='painting',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.artists'),
        ),
    ]
