# Generated by Django 3.1.2 on 2020-10-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_auto_20201027_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='artist',
        ),
    ]
