# Generated by Django 3.1.2 on 2020-10-28 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_painting_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exb_type', models.CharField(max_length=50)),
                ('exb_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('s_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('g_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('s_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('exb_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.exhibitions')),
            ],
        ),
    ]
