# Generated by Django 3.1.2 on 2020-10-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0020_auto_20201031_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='exb_id',
            new_name='exhibition',
        ),
        migrations.RenameField(
            model_name='exhibitions',
            old_name='g_id',
            new_name='gallary',
        ),
        migrations.AddField(
            model_name='exhibitions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
