# Generated by Django 3.1.2 on 2020-11-01 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0021_auto_20201031_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='likes',
            field=models.ManyToManyField(related_name='paintings', to=settings.AUTH_USER_MODEL),
        ),
    ]
