# Generated by Django 3.1.2 on 2020-11-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0022_painting_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='tot_likes',
            field=models.IntegerField(null=True),
        ),
    ]
